language: node_js
node_js: stable
sudo: required

before_install:
  - npm install -g hexo-cli

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - git config user.name "yb199478"
  - git config user.email "support@catlib.io"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - sed -i "s/gh_user/${GH_USER}/g" ./_config.yml
  - sed -i "s/gh_repository/${GH_REPOSITORY}/g" ./_config.yml
  - hexo deploy

branches:
  only:
    - 1.3
