# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: CatLib
author: catlib
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'https://seed.catlib.io/child' and root as '/child/'
url: https://catlib.io
root: /

# Writing
relative_link: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ../node_modules/hexo-theme-cookbook

ignore:
  - '**/node_modules/**/*node_modules'

deploy:
  - type: git
    repo: https://gh_token@github.com/gh_user/gh_repository.git
    branch: gh-pages

node_sass:
  includePaths:
   - node_modules

cookbook:
  partials:
    index:
      - _layout/index.ejs