environment:
  nodejs_version: "6"
  access_token:
    secure: 7pbe0TYPGE6wFfyLZwchNJELWGZDdntH6p7rsyzFRr4y/P8BX16AU/XYLVMRva65

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g hexo-cli
  - npm install

test_script:
  - node --version
  - npm --version

build_script: 
  - ps: hexo g

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com"
  - git config --global user.name appveyor
  - git config --global user.email support@catlib.io
  - git add .
  - git commit -am "gen docs"
  - git push origin master