environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g hexo-cli
  - npm install

test_script:
  - node --version
  - npm --version

build: 
  - hexo g