site_description: "CatLib Unity Framework."
root_domain: catlib.io
catlib_version: "1.0"
github: https://github.com/catlib/catlib
copyright: © Copyright 2017 catlib.io All Rights Reserved
copyright_desc: 喵喵喵，快来一起玩喵~